name: Sync minor from main

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-minor:
    runs-on: ubuntu-26.04

    steps:
      - name: Checkout main
        uses: actions/checkout@v6
        with:
          ref: main
          fetch-depth: 0

      - name: Reset minor to main
        run: git push origin HEAD:refs/heads/minor --force
